apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: decapod-controller
  source:
    path: hanu-reference/decapod-controller/argo-workflows-operator
    repoURL: https://github.com/seungkyua/oid-decapod-manifests.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
